### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by liamzebedee** [dappnetbby/dappnet-features#11]
- [x] replace SOCKS5 proxy with something prod-ready (Rust, based)
 - [x] automatic updates for dappnet software
 - [x] uncensorable/robust ENS lookups (https://github.com/gliss-co/dappnet-features/issues/9)
 - [ ] publish the extension to chrome webstore. get screenshots to match their format.
 - [ ] publish extension to firefox webstore. get screenshots to match their format.
 - [x] legal advice from Paradigm
 - [x] Configure the launch apps - Uniswap needs to be fixed (https://twitter.com/liamzebedee/status/1620585011077578752) 
 - [ ] Announcement
 - [ ] Download page + some sort of analytics

**Comment by liamzebedee** [comment]
Replaced with https://github.com/users/liamzebedee/projects/4/views/2?layout=board
